language: php
notifications:
  email: false
  slack: dervisgroup:EqIm58uQMIDcaSc9qyGUg1EK

php:
  - 7.2
# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache
    
before_install:
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer require dervisgroup/mobile-money:dev-master
  - cp ./vendor/dervisgroup/mobile-money/tests/config/.env ./
  - rm ./config/database.php
  - cp ./vendor/dervisgroup/mobile-money/tests/config/database.php ./config
  - touch database/database.sqlite
  - php artisan vendor:publish --provider="DervisGroup\Pesa\PesaServiceProvider"
  - php artisan migrate
  - cd ./vendor/dervisgroup/mobile-money
  
before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover